sudo: false
language: node_js
env:
  - MONGO_URI_TEST=mongodb://localhost/Testing
node_js:
  - "stable"
services:
  - mongodb
directories: -'node_modules'

cache:
  npm: false
notifications:
  email: false
script:
  - cd server
  - npm ci
  - npm run cover
after_success:
  - npm run coverage
