sudo: false
language: node_js
env:
  - MONGO_URI_TEST=mongodb://localhost/my-brand-test
  - PORT=3000
node_js:
  - "stable"
services:
  - mongodb
cache:
  npm: false
notifications:
  email: false
script:
  - npm ci
  - npm test
  - npm run cover
after_success:
  - npm run coverage
