sudo: false
language: node_js
env:
  - MONGO_URI_TEST=mongodb://localhost/Testing

node_js:
  - "stable"
services:
  - mongodb
cache:
  npm: false
notifications:
  email: false
script:
  - cd server/src
  - npm ci
  - npm test
  - npm run cover
after_success:
  - npm run coverage
